CrudWebApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace CrudWebApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

CrudWebApi/Models/CrudWebApiContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace CrudWebApi.Models
{
    public class CrudWebApiContext : DbContext
    {
        public CrudWebApiContext() : base("CrudContext")
        {
             
        }

        public DbSet<Employee> Employees { get; set; }
        
    }
}

CrudWebApi/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CrudWebApi.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string  EmpName { get; set; }
        public string Designation { get; set; }
    }
}

CrudWebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using CrudWebApi.Areas.HelpPage.Models;

namespace CrudWebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

CrudWebApi/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using CrudWebApi.Models;

namespace CrudWebApi.Controllers
{
    public class EmployeesController : ApiController
    {
        private CrudWebApiContext db = new CrudWebApiContext();

        // GET api/Employees
        public IQueryable<Employee> GetEmployees()
        {
            return db.Employees;
        }

        // GET api/Employees/5
        [ResponseType(typeof(Employee))]
        public async Task<IHttpActionResult> GetEmployee(int id)
        {
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            return Ok(employee);
        }

        // PUT api/Employees/5
        public async Task<IHttpActionResult> PutEmployee(int id, Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != employee.Id)
            {
                return BadRequest();
            }

            db.Entry(employee).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EmployeeExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST api/Employees
        [ResponseType(typeof(Employee))]
        public async Task<IHttpActionResult> PostEmployee(Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Employees.Add(employee);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = employee.Id }, employee);
        }

        // DELETE api/Employees/5
        [ResponseType(typeof(Employee))]
        public async Task<IHttpActionResult> DeleteEmployee(int id)
        {
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            db.Employees.Remove(employee);
            await db.SaveChangesAsync();

            return Ok(employee);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool EmployeeExists(int id)
        {
            return db.Employees.Count(e => e.Id == id) > 0;
        }
    }
}

CrudWebApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudWebApi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

CrudWebApi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" ng-controller="EmployeeController">
    <h2>{{PageTitle}}</h2>
    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Designation</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody ng-repeat="emp in employeeList" ng-switch="row.edit" ng-init="row={}">
            <tr>
                <td>{{emp.Id}}</td>
                <td>{{emp.EmpName}}</td>
                <td>{{emp.Designation}}</td>
                <td>
                    <input type="button" class="btn btn-group-sm btn-warning" name="Edit" value="Edit" ng-click="getEmployee(emp.Id);row.edit=true" />
                    <input type="button" class="btn btn-group-sm btn-danger" name="Edit" value="Delete" ng-click="deleteEmployee($index,emp.Id)" />
                </td>
            </tr>
            
            <tr ng-switch-when="true">
                <td>{{emp.Id}}</td>
                <td>
                    <div class="input-group">
                        <span class="input-group-addon">Name:</span>
                        <input type="text" class="form-control" ng-model="emp.EmpName" ng-value="emp.EmpName" required="required">
                    </div>
                </td>
                <td>
                    <div class="input-group">
                        <span class="input-group-addon">Designation:</span>
                        <input type="text" class="form-control" ng-model="emp.Designation" ng-value="emp.Designation" required="required">
                    </div>
                </td>
                <td>
                    <button type="button" class="btn btn-success btn-sm" ng-click="editEmployee(emp) ; row.edit=false">
                        <span class="glyphicon glyphicon-save"></span> Save
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
    
    <br/>
    
    <div class="row">
        <table class="table table-striped table-bordered">
            <tbody>
                <tr ng-if="states.showEmpForm">
                    <td>
                        <div class="input-group">
                            <span class="input-group-addon">Employee Name</span>
                            <input type="text" class="form-control" ng-model="new.Employee.EmpName" required="required">
                        </div>
                    </td>
                    <td>
                        <div class="input-group">
                            <span class="input-group-addon">Designation</span>
                            <input type="text" class="form-control" ng-model="new.Employee.Designation" required="required">
                        </div>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" ng-click="addEmployee()"> Add</button>
                        <button type="button" class="btn btn-default" ng-click="showEmpForm(false)">Cancel</button>
                    </td>
                </tr>
            </tbody>
        </table>
        <a ng-click="showEmpForm(true)" class="btn btn-primary">New</a>
    </div>

</div>



@section scripts
{
<script src="~/CustomScripts/App.js"></script>
<script src="~/CustomScripts/EmployeeCtrl.js"></script>
}

CrudWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="MyApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>